services:
  - type: web
    name: qa-app-server
    runtime: node
    buildCommand: NODE_ENV=development npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: $HOME/.cache/ms-playwright
